version: "3.9"

services:
  mcp_server:
    build:
      context: .
      dockerfile: dockerfile
    command: python -m backend.mcp.mcp_server
    environment:
      - MCP_PORT=${MCP_PORT}
    ports:
      - "${MCP_PORT}:${MCP_PORT}"
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn backend.api.api:app --host 0.0.0.0 --port ${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    command: streamlit run frontend/app.py --server.port ${FRONTEND_PORT} --server.address 0.0.0.0
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped